spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/financial_reconciliation_system}
spring.datasource.username=${navindurajamanthri:postgres}
spring.datasource.password=${navsand123#:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
