spring.application.name=frwss

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/frwss;MODE=PostgreSQL;AUTO_SERVER=TRUE}
spring.datasource.username=${navindurajamanthri:sa}
spring.datasource.password=${navsand123#:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
