spring.application.name=frwss

# Replace 'your_db_name' with the name you created in pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/financial_reconciliation_system

# the credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# This tells Spring to update your table structure automatically
# the driver and hibernate logic
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true