spring.datasource.url=jdbc:postgresql://localhost:5432/financial_reconciliation_system
spring.datasource.username=postgres
spring.datasource.password=as%Eb370

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true